### ISSUE TITLE
piu files

### ISSUE THREAD

**Issue by abitrolly** [keithieopia/piu#14]
What do you think about adding `piu files` for listing files provided by a package?

For `dnf` based installs it would be `dnf repoquery -l` with optional `-C` flag to avoid cache update.

**Comment by keithieopia** [comment]
That seems like a great idea to add. I know pacman has similar functionality as well as apt. I'd be happy to accept a pull request, even if it's just for dnf.

Otherwise, I'll work on adding support in my free time

**Comment by keithieopia** [comment]
### TODO

#### Research PKG MGR Invocations
- [x] `dnf`
  - `dnf repoquery -Cl $1`
- [ ] `apt`
- [ ] `xpbs-`
- [ ] `pacman`
- [x] `zypper`  :construction:  _not implemented yet, see #15_
  - `find /var/cache/zypp -name $1 | rpm -ql`

#### Add individual package manager functions
- [ ] `dnf`
- [ ] `apt`
- [ ] `xpbs-`
- [ ] `pacman`

#### Implement piu files invocation
- [ ] help text
- [ ] files argument
  - [ ] -f abbreviation 

#### Final Testing
- [ ] `dnf`
- [ ] `apt`
- [ ] `xpbs-`
- [ ] `pacman`

**Comment by abitrolly** [comment]
@keithieopia the correct `dnf` command is `dnf -C repoquery -l $1` or `dnf --cacheonly repoquery --list $1`.

Nice TODO. )

**Comment by keithieopia** [comment]
Thank you for the clarification, I've updated the TODO

**Comment by keithieopia** [comment]
`piu files` has been implemented for all of the supported package managers!

- I'm not happy with the Arch Linux code, but _"rather something than nothing"_. I'd love some help refactoring it.
- Alpine Linux's code has some quirks, but the issues are upstream with `apk`
