### ISSUE TITLE
OpenSUSE / zypper

### ISSUE THREAD

**Issue by keithieopia** [keithieopia/piu#15]
Add support for `zypper` which is OpenSUSE's package manager

**Comment by keithieopia** [comment]
- [ ]  (i)nstall - `sudo zypper in $1`
- [ ]  (r)emove
- [ ]  (p)urge
- [ ]  (s)earch - `zypper search $1`
- [ ]  (m)anual - `sudo zypper in $1`
- [ ]  (u)pdate - `sudo zypper up`
- [ ]  (c)ache - `sudo zypper ref`
- [ ]  (l)ist
- [ ]  (nu) num-updates
- [ ] (np) num-packages

**Comment by gtsop** [comment]
Just a suggestion here, in [this PR](https://github.com/keithieopia/piu/pull/17/) i've got a function that can be very useful for ensuring a package manager wrapper has implemented the full interface. Will probably help to keep things in line as the interface and the managers grow.

https://github.com/keithieopia/piu/pull/17/files#diff-04d7e0ccb27079600cba088e7fd6106aa39a43949370178707916343e6e206b6R37-R45
