### ISSUE TITLE
Package for Homebrew

### ISSUE THREAD

**Issue by abitrolly** [keithieopia/piu#22]
It would be convenient to install/update `piu` with `brew` instead of copy/pasting `curl` command. I can [create the formula](https://docs.brew.sh/Adding-Software-to-Homebrew), but the repo needs to carry version tags for the latest and greatest release.

**Comment by keithieopia** [comment]
Was out of town, sorry for the delay. piu is now at v1.1

By the authority vested in me, I hereby designate you, @abitrolly, piu's *erm...* "brewmaster", *no....* "brew formulator?", *that's not right either...* "macOS lead developer" *too pretentious...* Well, whatever. You have my blessings to create the formula. 

Thank you in advance for making piu more accessible to users!

**Comment by rokejulianlockhart** [comment]
@abitrolly, has this been added yet?

**Comment by abitrolly** [comment]
@rokejulianlockhart no, I run out of money and spend my days in depression.
