### ISSUE TITLE
Manjaro Linux: `piu u` does not upgrade packages

### ISSUE THREAD

**Issue by Rocka84** [keithieopia/piu#3]
Hi,
first of all: Thanks for this tool, it will save time and prevent headaches!

When using `piu u` on my manjaro machine, this script executes the command `pacman -Sy`, which does not upgrade packages but only updates the cache of pacman. The correct command would be `pacman -Syu` or `pacman -Syyu`.

Rocka84

**Comment by keithieopia** [comment]
@Rocka84 thank you so much for the kind words and taking the time to report that. The latest version of `piu` should be fixed now.
 
piu has logic to handle updating the package cache if it's old, so the command I changed it to was `pacman -Su` (`pacman -Syu` updates the cache *and* upgrades the system). 

piu automatically does a `pacman -Sy` beforehand if pacman's cache is older than 12 hours (you can change this by editing `UPDATE_AFTER` on the 3rd line of the script).
