### ISSUE TITLE
Brew errors when passed -y

### ISSUE THREAD

**Issue by jaron-l** [keithieopia/piu#30]
I use this package to write cross platform set up scripts. As part of that script, I need to install several packages. On at least apt, dnf, and yum, if you want to install a package without a confirmation prompt, you have to pass a “-y" confirmation flag; however, on brew, there is no confirmation flag so the command always fails when passing the flag.

I could probably pretty easily write a PR to make this package not pass on the "-y" flag to brew. Any other ideas on a better way to handle this?

**Comment by keithieopia** [comment]
I'm glad you're finding piu useful. I'd gladly accept a PR for -y flag issue on brew.
